### ISSUE TITLE
Is this the source code for the jdk binaries in Tinycore?

### ISSUE THREAD

**Issue by dsyer** [Zlika/tce#4]
I downloaded some JDK/JRE binaries using `tce-load`. They seem broken in respect of some native libraries. Is this the source code repo? What's the process to make changes in http://distro.ibiblio.org/tinycorelinux/11.x/x86/tcz/?

**Comment by Zlika** [comment]
Hi.
This was the script I used to compile the JDK/JRE binaries for Tiny Core 7. I submitted the binaries by email (cf. http://forum.tinycorelinux.net/index.php?topic=330.0 for the process).

**Comment by thirdwheel** [comment]
Did you get the errors I described in #2?

**Comment by Zlika** [comment]
No sorry. I tried to google the exception message but I didn't find anything. Did you use the full JRE or a compact profile? Are you sure this version of minecraft is compatible with java 8?

**Comment by dsyer** [comment]
Similar. Probably the same cause. I gather that was fixed but not released (the release process is a little unclear)?

**Comment by Zlika** [comment]
Tiny core's release process is completly obscure, and there is no clear link between the sources and the generated binary packages. That's why I switched to buildroot.

**Comment by dsyer** [comment]
Interesting. Do you have any notes on how to install OpenJDK on buildroot?

**Comment by Zlika** [comment]
OpenJDK is available on Buildroot, but Buildroot requires you to configure and build your operating system from sources, so it's more complex to use than Tiny Core, but also much more powerful and flexible.

**Comment by dsyer** [comment]
I can see the openjdk package in buildroot. And I can run "make" and generate output. I'm just not able to stitch it all together yet. If you have a recipe that would be helpful (e.g. a .config file).

**Comment by Zlika** [comment]
Sorry I don't have such a recipe because I mostly use Buildroot for the rapsberry pi, and for these small platforms I prefer to use python instead of java.

**Comment by dsyer** [comment]
Thanks. I got something to work. It's a bit hard to work out which packages / options to enable. Maybe I'll write it up when I finish.
